# Generated by Django 5.0 on 2024-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_manage', '0002_rename_offer_expire_brandoffer_offer_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='offer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='offer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
